Feature/6 torch losses (#17)
* added masked_spectral_distance_torch loss - torch equivalent for masked_spectral_distance

* added masked_spectral_distance_torch to init

* added typing-extensions>=4.8.0 to setup.py due to ImportError: cannot import name 'TypeIs' from 'typing_extensions'  --> TODO: resolve version conflict with tensorflow version!

* test for equivalency of output of the tf & the torch version of masked_spectral_distance

* updated docstring & added type hints

* added masked_pearson_correlation_distance_torch to init

* added 3 test equivalents for masked_pearson_correlation_distance, similar to masked_spectral_distance

* added torch equivalent for masked_pearson_correlation_distance

* added type hints & adjusted docstring

* added test for equivalence of torch & tf masked_pearson_correlation_distance loss

* had to add unbiased=False to torch.std() to make it equivalent to tf.math.reduce_std()

* changed tf torch loss output comparison to np.allclose()